version: '2.3'

services:


  ftphoneypot:
    container_name: ftp
    restart: always
    network_mode: "host"
    image: "hary654321/ftp"
    volumes:
     - $PWD/data/ftp/log:/var/log/ftp
    environment:
      HP_PORT: "1234"
      LOGIN_PWD: "pwd"
      LOGIN_NAME: "a"